// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn86ZwMMub3X3gYATqsAaRka_o-JcjstE',
    appId: '1:16291153417:web:fde8ac3a807d9596539ad8',
    messagingSenderId: '16291153417',
    projectId: 'mynotes-flutter-project-ege',
    authDomain: 'mynotes-flutter-project-ege.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-ege.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB92WqYZoZDF08RUZ-knN_08xi_7ejAc80',
    appId: '1:16291153417:android:606c99047b7eaf26539ad8',
    messagingSenderId: '16291153417',
    projectId: 'mynotes-flutter-project-ege',
    storageBucket: 'mynotes-flutter-project-ege.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbeiOApqppylCRpZf8k7hbNvZ3vzzwtGU',
    appId: '1:16291153417:ios:e58f9e553edff6dd539ad8',
    messagingSenderId: '16291153417',
    projectId: 'mynotes-flutter-project-ege',
    storageBucket: 'mynotes-flutter-project-ege.appspot.com',
    iosClientId: '16291153417-kqr2a3u7vukaf5d58hjferv67nhnoslt.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbeiOApqppylCRpZf8k7hbNvZ3vzzwtGU',
    appId: '1:16291153417:ios:e58f9e553edff6dd539ad8',
    messagingSenderId: '16291153417',
    projectId: 'mynotes-flutter-project-ege',
    storageBucket: 'mynotes-flutter-project-ege.appspot.com',
    iosClientId: '16291153417-kqr2a3u7vukaf5d58hjferv67nhnoslt.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
